add usdc and osmo
CoreumFoundation/token-registry pull request #6
Opened 2024-01-15 15:35 UTC by wanesurf

2024-01-15 15:55 UTC, akhlopiachyi requested changes

2024-01-15 15:55 UTC, akhlopiachyi commented on mainnet/assets.json
> +                "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/USDCoin.svg"
images should be inside of this repo, not somewhere else

2024-01-15 15:55 UTC, akhlopiachyi commented on mainnet/assets.json
> +                "whitepaper": "#"
if there is not whitepaper link, don't set it here

2024-01-15 15:55 UTC, akhlopiachyi commented on mainnet/assets.json
> +                "tiktok": "#"
if there is not links, don't set them here to #

2024-01-15 15:55 UTC, akhlopiachyi commented on mainnet/assets.json
> +                "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/osmo.svg"
the same as above

2024-01-15 15:55 UTC, akhlopiachyi commented on mainnet/assets.json
> +                "tiktok": "#"
the same as above

2024-01-15 22:00 UTC, wanesurf reviewed
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/6)* status: all files reviewed, 5 unresolved discussions (waiting on @akhlopiachyi, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`mainnet/assets.json` line 35 at r1](https://reviewable.io/reviews/CoreumFoundation/token-registry/6#gh-1452540697:-NoE7xFv366QX9nENSP7:b-896fix) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/2c9ff9ffcb9ab11c9648bef280012fe149f63e7c/mainnet/assets.json#L35)):*
<details><summary><i>Previously, akhlopiachyi (Alex Khlopiachyi) wrote…</i></summary><blockquote>

images should be inside of this repo, not somewhere else
</blockquote></details>

Done.
___
*[`mainnet/assets.json` line 40 at r1](https://reviewable.io/reviews/CoreumFoundation/token-registry/6#gh-1452541285:-NoE7xfo33-DZVgtsZUj:b-896fix) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/2c9ff9ffcb9ab11c9648bef280012fe149f63e7c/mainnet/assets.json#L40)):*
<details><summary><i>Previously, akhlopiachyi (Alex Khlopiachyi) wrote…</i></summary><blockquote>

if there is not whitepaper link, don't set it here
</blockquote></details>

Done.
___
*[`mainnet/assets.json` line 50 at r1](https://reviewable.io/reviews/CoreumFoundation/token-registry/6#gh-1452541827:-NoE7y1f61POGqCPi5-r:b-896fix) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/2c9ff9ffcb9ab11c9648bef280012fe149f63e7c/mainnet/assets.json#L50)):*
<details><summary><i>Previously, akhlopiachyi (Alex Khlopiachyi) wrote…</i></summary><blockquote>

if there is not links, don't set them here to #
</blockquote></details>

Done.
___
*[`mainnet/assets.json` line 61 at r1](https://reviewable.io/reviews/CoreumFoundation/token-registry/6#gh-1452542091:-NoE7ySE06axJDr4X5UQ:b-896fix) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/2c9ff9ffcb9ab11c9648bef280012fe149f63e7c/mainnet/assets.json#L61)):*
<details><summary><i>Previously, akhlopiachyi (Alex Khlopiachyi) wrote…</i></summary><blockquote>

the same as above
</blockquote></details>

Done.
___
*[`mainnet/assets.json` line 76 at r1](https://reviewable.io/reviews/CoreumFoundation/token-registry/6#gh-1452542233:-NoE7ytm-Xpvzmag2THK:b-896fix) ([raw file](https://github.com/CoreumFoundation/token-registry/blob/2c9ff9ffcb9ab11c9648bef280012fe149f63e7c/mainnet/assets.json#L76)):*
<details><summary><i>Previously, akhlopiachyi (Alex Khlopiachyi) wrote…</i></summary><blockquote>

the same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-16 11:20 UTC, akhlopiachyi reviewed
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/token-registry/6)* status: all files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum and @ysv)



<!-- Sent from Reviewable.io -->

2024-01-16 11:21 UTC, merged